#!/bin/bash
# Quick Start Guide for Orchestration Team
# Run this to see the main orchestration commands

echo "======================================================================"
echo "   ORCHESTRATION TEAM - QUICK START GUIDE"
echo "======================================================================"
echo ""
echo "Location: sprint/day1/orchestration/"
echo ""
echo "MAIN COMMAND:"
echo "  ./orchestration_cli.py [command]"
echo ""
echo "======================================================================"
echo "MOST USEFUL COMMANDS"
echo "======================================================================"
echo ""
echo "1. QUICK STATUS (use this most often!)"
echo "   ./orchestration_cli.py status"
echo ""
echo "2. HOURLY CHECKPOINT (run at hours 2, 4, 6, 8)"
echo "   ./orchestration_cli.py checkpoint 2"
echo "   ./orchestration_cli.py checkpoint 4"
echo "   ./orchestration_cli.py checkpoint 6"
echo "   ./orchestration_cli.py checkpoint 8"
echo ""
echo "3. VIEW SPECIFIC TEAM"
echo "   ./orchestration_cli.py team team1_google_oauth"
echo "   ./orchestration_cli.py team team2_microsoft_oauth"
echo "   ./orchestration_cli.py team team3_api_clients"
echo "   ./orchestration_cli.py team team4_testing"
echo "   ./orchestration_cli.py team team5_token_security"
echo ""
echo "4. MANAGE BLOCKERS"
echo "   # List all blockers"
echo "   ./orchestration_cli.py blocker --list"
echo ""
echo "   # Create a blocker"
echo "   ./orchestration_cli.py blocker \\"
echo "     --team team1_google_oauth \\"
echo "     --description \"Base class design blocked\" \\"
echo "     --severity P0 \\"
echo "     --impact \"Blocks Team 2\" \\"
echo "     --affected team2_microsoft_oauth"
echo ""
echo "5. FULL DASHBOARD"
echo "   ./orchestration_cli.py dashboard"
echo ""
echo "======================================================================"
echo "INDIVIDUAL TOOLS (if you need more detail)"
echo "======================================================================"
echo ""
echo "Progress Tracker:"
echo "  ./track_progress.py --dashboard"
echo "  ./track_progress.py --milestone 4"
echo ""
echo "Team Coordination:"
echo "  ./team_coordination.py standup team1_google_oauth"
echo "  ./team_coordination.py report 4"
echo "  ./team_coordination.py blockers"
echo ""
echo "Blocker Management:"
echo "  ./blocker_management.py list"
echo "  ./blocker_management.py details BLK-ID"
echo ""
echo "======================================================================"
echo "WORKFLOW"
echo "======================================================================"
echo ""
echo "Hour 0 (Kickoff):"
echo "  1. ./orchestration_cli.py status"
echo "  2. Brief each team on their TODO"
echo ""
echo "Hours 2, 4, 6 (Checkpoints):"
echo "  1. ./orchestration_cli.py checkpoint [HOUR]"
echo "  2. Review with all teams"
echo "  3. Address any blockers"
echo ""
echo "Hour 8 (Final):"
echo "  1. ./orchestration_cli.py checkpoint 8"
echo "  2. Export metrics: ./track_progress.py --export final.json"
echo "  3. Celebrate! 🎉"
echo ""
echo "======================================================================"
echo "For full documentation, see: README.md"
echo "======================================================================"
echo ""
